### ISSUE TITLE
What platform / tech stack do you use for your personal blog?

### ISSUE THREAD

**Issue by ghost** [aspittel/ama#10]
Hi Ali,

I have been blogging for about a year on Medium and am thinking of creating a personal blog site too. I have looked into options, such as Wordpress.com, Gatsby.js / Hugo with Netlify, and am interested in what other bloggers use.

What platform or tech stack do you use for your personal site at https://zen-of-programming.com/

Keep up the great work!

Ryan

**Comment by aspittel** [comment]
Hey Ryan!

I use Gatsby with Netlify and I love it -- [here's](https://github.com/aspittel/zen-of-programming) the code for it!

Thanks,
Ali
