### ISSUE TITLE
Web development workflow

### ISSUE THREAD

**Issue by sangeethaKP** [aspittel/ama#11]
I am working on a web application as a side-project. I have my requirements, features and UI mock-ups in Sketch ready and narrowed down for the Beta launch of the app. The task of actually building the website remains open. What is the usual workflow you take to build a web application - I believe the many steps involved are 
0. Getting the back-end data store ready 
1. Getting the APIs defined and ready 
2. Define routing within the application 
3. Building the front end 
4. Hooking different components up 
5. Deployment and many more I suppose.. 

This is my first time building a web-application solo from scratch. From your experience, how do you suggest to approach the web development process?

**Comment by aspittel** [comment]
Hey! I think that process is great. 

I would start with designing, wireframing, and planning out the data I need for the application. Then, I would add comments to "outline" the methods I'll need. Then I'd start coding the API.

Then I would move over to the front end using the planning I created previously!

Deployment would be the last step. I would keep the front and back ends separate if you are using React and just deploy the API and front end separately.

Good luck!
