### ISSUE TITLE
I Cloned Your Personal Website! :/

### ISSUE THREAD

**Issue by benwinding** [aspittel/ama#12]
Hi Ali,

For over a year I've been been trying to create my own personal portfolio site because I thought it would be a fun and creative way to catalogue my own stuff!

I did a lot of research and found dozens of epic portfolio sites and yours was one of them! Using all these portfolio's as inspiration I tried making my own site from scratch... but it was really hard. Even though I knew what looked good and bad, I couldn't believe how difficult it was to make something _actually look good!_ I went through so many different designs, most of which you can [see here](https://old.benwinding.com/old-site/). 

![old site](https://i.imgur.com/5ZYL3X2.png)

Then I saw on Hacker News [this article](https://zen-of-programming.com/kickass-portfolio/) and recognised the portfolio as one listed in my favourites. It suddenly occurred to me that I was wasting so much time trying to make my own website from scratch that I hadn't looked at anyone else's code! So I decided to search for the source for your site and was grateful that you [open-sourced](https://github.com/aspittel/aspittel.github.io/) the code! 

So I sneakily cloned it and starting hacking away making it my site. I wanted it to be different, but didn't want to change it to drastically (because I struggled to make anything look good).

![new site](https://i.imgur.com/6owvxv1.png)

Anyway, this was a long way of saying thank you :tada: for open-sourcing your personal site to help out those of us that suck at design! [Here's my source code](https://github.com/benwinding/benw-portal) and the site is finally live at  [https://benwinding.com](https://benwinding.com).

Sincerely,
Ben

**Comment by aspittel** [comment]
Ah awesome, glad it was helpful! Thanks for passing this along!

**Comment by peoray** [comment]
@benwinding can't find any license on the repo?
