### ISSUE TITLE
How did you get in to web development?

### ISSUE THREAD

**Issue by ghost** [aspittel/ama#4]
What was your path to becoming a web developer like, and if you were to start over what would you do differently?

**Comment by aspittel** [comment]
I'll write out a longer answer at some point as a blog post, but my path was kind of weird -- I never really wanted to be a web developer until I was one. I had taken some computer science in college, but it was kind of a roller coaster. I would love it then hate it and then the cycle would start all over again. I then ended up getting a job that was part software engineering part my career path at the time, which was politics. I really liked doing the software engineering stuff and moved more and more in that direction.

If I were to start over, I would learn how to code before college computer science -- I think those programs aren't geared towards teaching people to code, they're for teaching computer science concepts. I wish I had learned HTML and CSS even in high school, like I know a lot of people do. I also wish I had more confidence -- I thought I was really bad at first and so I wasn't as serious about it as I could have been!
