### ISSUE TITLE
How is your name pronounced?

### ISSUE THREAD

**Issue by arximughal** [aspittel/ama#8]
Just wondering, how is your name pronounced?
No offense, In my country, *Ali* is a usually a boy's name. So, I am just wondering if its probably pronounced differently than ours!

**Comment by aspittel** [comment]
Just like the name Allie -- its short for the name Alison! [Here's](https://www.youtube.com/watch?v=Ts8dJ6tFKQA) a YouTube video with someone saying it!

**Comment by arximughal** [comment]
Great. Thanks for taking time to reply to this [stupid] question 😛 
BTW, here's [how "ALI" is pronounced](https://youtu.be/S8jpYM6Q__Q?t=7) in my country.
