### ISSUE TITLE
In The Cloud

### ISSUE THREAD

**Issue by michaelgv** [aspittel/ama#9]
Hey,

I noticed your website (zen-of-programming) is on google's cloud infrastructure, just curious how much that's costing you to run, and what module you rely on to run it? (ie, k8s, static, vms, etc)

Cheers

**Comment by aspittel** [comment]
Oh interesting! I actually use Netlify -- behind the scenes they must be using Google Cloud. I use the free version and use the feature that runs your build script and deploys every time you push to GitHub. I can't recommend it highly enough!
